### ISSUE TITLE
World map marker facets are off by 1 starting from Trammel

### ISSUE THREAD

**Issue by comiluv** [ClassicUO/ClassicUO#1030]
Not sure this is intended or not but thought this would need confirmation.
map files and xml files from either UOAM or Ultima Mapper numbers Ilshenar to be facet number 3 and counts onward.
So Felucca is 0, Tram is 1, Ilshenar 3, Malas 4, Tokuno 5, and Ter Mur is 6 in UOAM and Ultima Mapper's default files.
Whereas in ClassicUO Fel is 0 and Tram is 1 and it's identical up to this point but Ilshenar is 2, Malas 3 and so on.
This is easy to fix on client side by replacing Facet="n" to Facet="n-1" and iterating from 2.

This is tested on ServUO Publish 57 (https://github.com/ServUO/ServUO/releases/tag/57)

**Comment by comiluv** [comment]
Also, while in Trammel, world map should display icons and labels with Facet 2 and Facet 0, and while in Felucca, world map should display data from labels Facet 0 and 1. Facet number 1 is Felucca-only places such as Ocllo and the world map should display those and Face 2 is Tram, by looking at .map and .xml files in UOAM and Ultima Mapper

**Comment by markdwags** [comment]
Yep, in UOAM world, 0 = both, 1 = Fel, 2 = Trammel, etc. At the moment, while the implementation was added to help import your UOAM and Mapper files, as you note, it doesn't mimic that logic exactly.

With this implementation, at least at the moment, the number is based on the map index from the server and in the client. So, for most servers, index 0 is Fel, 1 is Trammel, etc. 

I personally like this approach as I believe it's easier instead of having 0 mean 1 and 2, but not 3 or 4, etc.  This makes it easier for shards to support custom maps since not all shards follow the normal pattern.
