### ISSUE TITLE
doubloon/gold ghost items

### ISSUE THREAD

**Issue by ichiokada** [ClassicUO/ClassicUO#1155]
this bug persist for a long while, even on newest dev
- only doubloons and gold
- seems only happen when im in ocean

im currently on classicUO .968 (outlands launcher ver)

https://streamable.com/tco8mj

![image](https://user-images.githubusercontent.com/48904458/87651729-d832b100-c785-11ea-9ee5-99c2480772bd.png)

**Comment by andreakarasho** [comment]
Note:
- from latest feedback seems it happens more when using Razor + objects queue.

**Comment by SaschaKP** [comment]
Razor + objects queue has a bug in the queue handling, since the items won't be removed from the dictionary after the lift packet is sent, so when you try to lift an object, it requests a lift of something that maybe isn't in that particular position or doesn't exists anymore, my recent pull request into https://github.com/markdwags/Razor should have solved it, but I don't know if outlands pulled it.

**Comment by andreakarasho** [comment]
https://github.com/andreakarasho/ClassicUO/issues/994#event-3687345325
