### ISSUE TITLE
Security of password stored in settings.json

### ISSUE THREAD

**Issue by beevik** [ClassicUO/ClassicUO#1162]
I've noticed that the password stored in `settings.json` is an easily reversible mangling of the password that uses the machine name as a key.  This isn't very secure, especially since the settings file is typically readable by anyone with access to the system.

On Windows systems, have you considered using the Windows Credential Manager to make this more secure?  I'd be happy to submit a backwards-compatible pull request implementing this change if you are open to it.

**Comment by Alias-Alan** [comment]
What is the issue though? unless you are sharing this file publicly you have the only copy. Am i missing something such as a reason this file would be distributed ?

**Comment by LeopoldUOR** [comment]
People might sometimes share the settings.json file to others to help them connect to a server.  Yes, it's true they shouldn't, or they should at least delete the "password" field, or they should instead point people to a launcher.  But for some people it might be very tempting to simply say "here - put this file in your CUO directory."  I've shared screenshots of my settings.json (without sharing any username/password info) several times for this reason.

**Comment by oroechimaru** [comment]
As a multios app this is probably a pain to maintain. My suggestion is moving the encrypted password to a separate json file for account management. I have seen people post their passwords and often have access via teamviewer (trust), this may reduce the risk of human error.

**Comment by beevik** [comment]
It's true that the password is visible only to people with access to the machine.

What bothers me about the badly encrypted password in the `settings.json` file is that it gives the user a false sense of security.  The password looks like it's encrypted, but it's really not.  As @LeopoldUOR points out, this could lead people to share the entire file (on discord, pastebin, etc.). Imagine a malicious person hanging out in discord waiting for someone needing help with a UO client issue.  They'd say, "Send me your `settings.json` file so I can help you out."   A lot of people would fall for it.  Perfect opportunity to steal accounts.

Moreover, the `settings.json` file is stored in a common directory (`Program Files (x86)`) instead of in a user's `%APPDATA%` directory, so anyone with an account on the machine can read it regardless of their admin status.  (This is actually a separate problem in many ways, and should probably have its own issue.  Storing user-specific data in the application directory just seems wrong.)

In general, storing plaintext passwords on disk is frowned upon by security experts, and things like this would normally fail a security audit.

In my opinion, the best solution would be to rely on the OS's secure credential storage mechanisms. 

The second best solution would be to store the current settings data in the user's `%APPDATA%` (or `.config`) directory.

The third best (but still not very good) solution would be to simply store the password in plaintext, so at least the user looking at it will be less tempted to share it.

**Comment by oroechimaru** [comment]
There has been back and forth discussions of using appdata, again this doesnt work for linux and macos since those are different os or mobile cuo. I think for a 20 year old game its fine, or optionally DONT use the future, or have password in another file (not settings) etc. multi use computers for cuo is like < 10 out of 2000+ users i dont know how much of a security issue it is.


Out of 1500+ people we have helped ive seen 1-2 people only post their settings password on accident and maybe 2 that were worried someone would steal it on teamviewer.

I just dont think its a major security issue.

**Comment by beevik** [comment]
It would be pretty trivial to store `settings.json` in a user directory (`%APPDATA%` on Windows, or `.config` on linux/mac).  Probably just a few lines of code.

**Comment by SaschaKP** [comment]
password can be stored only in Environment.SpecialFolder.LocalApplicationData, for systems like *nix and mac, since other evironment folders aren't suitable for this use, especially since macos is more strict about this.

*nix:
LocalApplicationData => /home/$USER/.local/share

Windows Vista and later
LocalApplicationData: C:\Users\username\AppData\Local

mac
LocalApplicationData => /home/$USER/.local/share
