### ISSUE TITLE
[OSI] hp not updated

### ISSUE THREAD

**Issue by ziox-b** [ClassicUO/ClassicUO#1219]
one problem I'm running into thought, is that the health bar of mobiles not updating properly. You have to pull the bar to get it update to the real % life value.

OSI

**Comment by Alias-Alan** [comment]
@ziox-b does everything else for mobile update: (health over head %), healthbar below character?

**Comment by ziox-b** [comment]
head %, line bar have same issue. when you pull the bar it refresh the real % life value.

**Comment by sirdonpiano** [comment]
I can add that, for me, this issue occurs after being logged in and playing for a bit. However, it does not affect my pet's bar. Just all other mobiles.

Running around a populated area (npcs or players) will expedite the issue. Staying in area with a single NPC will allow health bar to update properly for 20+ minutes.

Fixed by closing/reopening client.

**Comment by andreakarasho** [comment]
Pushed a fix. 
Let me know please

**Comment by sirdonpiano** [comment]
Tried testing it again. The issue does seem to be better. After a while core issue still seems to occur, but the fix you put in place frequently corrects the issue when it begins occurring after killing mobs for a bit. I'd call this a 90% main health bar fix. It's certainly playable now.

Can still get it to semi-reliably break during longer play session when closing health bar. This will cause health bar below mob and the percentage above to stop updating until health bar is pulled again or mob dies.
