### ISSUE TITLE
Water tiles and surrounding lines

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#1222]
When you have water tiles and statics meet, you can see the lines that are to connect them and the sand below the water. This happens at most of the zoom levels but it does not at zoom level 5. I am running this with today's dev version of 0.1.5.32.

![image](https://user-images.githubusercontent.com/49735284/94291262-00c2ee00-ff21-11ea-88b4-10dd49abe34b.png)

**Comment by andreakarasho** [comment]
These artifacts are due to the new rendering engine.
The way ClassicUO used to render was totally wrong and a waste of resources. So i adapt the render to the standard one or in other words: this is how things must be done.
The main effect is a 20/40% more of performances and better scalability, but from the other side we can meet issues like above. Let me remember that UO textures are not made to be scaled [they are simply PNG files]. Pixels can "collides" each others or overlap.
Why things worked before? Simply each frame we push all pixel data to an huge texture and then we scaled this single texture.
