### ISSUE TITLE
Character creation name field needs character restrictions

### ISSUE THREAD

**Issue by brndd** [ClassicUO/ClassicUO#1281]
In the original client the only characters allowed seem to be, in regex form, `[A-z0-9\-']`, so alphanumerics, hyphen and apostrophe. In CUO you can enter any character, which on most servers seems to get you stuck in the "loading screen" after character creation as the name is invalid.

Adding an option to `StbTextBox` to restrict the set of allowed characters using eg. a regular expression would be good.

**Comment by SaschaKP** [comment]
I would personally use the same way runuo and other server check for a valid name.

It should be pretty easy, and would allow for easier manipulation.

**Comment by SaschaKP** [comment]
b8b504f58e3b2c73f41f66c8819af0bd842d8aef should fix that issue, but I bet it needs a double check to assure we are doing exactly the same thing as the original client. if post 6.0.14.2 numbers are allowed in names, please report that variation, since any version prior to 6.0.14.2 doesn't allow numbers in name.

**Comment by SaschaKP** [comment]
If there is something wrong with this solution, write a response, I'll recheck it ASAP.
