### ISSUE TITLE
Assistant

### ISSUE THREAD

**Issue by 3HMonkey** [ClassicUO/ClassicUO#132]
**Describe the solution you'd like**
Assistant should be added.

**Comment by SaschaKP** [comment]
I suppose this is something hard to do, I was also thinking a pair of ideas, but everything you add can make it bad...

One idea was to emulate the macro style of assistuo/UOSteam, since I've already worked with pseudo language style systems (XMLSpawner in RUNUO, that I've maintained for a lot of time), it could come handy, since there are a pair of tricks that could be used to add a scripting language to razor itself, eg: a textarea where you can add a script operation (a macroaction that comprises the whole script), but we must also face the fact that something like this could ruin the client...

**Comment by efftq** [comment]
Just passing by:

+1 to what [uoitalia](/uoitalia) suggested - add scripting to the client itself, don't care about loaders/assists in another process.
That would allow us, people who use Linux/OSX to finally stop using wine and all that shit that doesn't really work.

Even limited razor-like scripting (i.e. where I don't have a free editor and have to add lines / select commands) is better than nothing; you already have a limited macro functionality, just add some if/while support to that and we are good to go :-)
Also, the idea with assist in another process made sense with osi client where we didn't control the source code; we don't what that problem anymore and can extend the client itself.

**Comment by darthdeus** [comment]
Is there some way I could help with this, or in general with adding UOSteam macro support to either CUO, or the modified Razor version? I've written more than one interpreter in the past, so I wouldn't mind doing the same for UOSteam macros, or at least helping with it in some way.

**Comment by andreakarasho** [comment]
just FYI https://github.com/jaedan/steam-engine

**Comment by darthdeus** [comment]
@andreakarasho Thanks! Is that what the current UOSteam support is being blocked on? I'd really want to help move this feature along, but @Jaedan doesn't have contact info on his profile, so uhm, not really sure what specifically needs to be done there apart from the lists/aliases TODO. Any thoughts?

**Comment by andreakarasho** [comment]
Jaedan is often online in discord. https://discord.gg/VdyCpjQ

**Comment by andreakarasho** [comment]
I don’t want to mix things.
