### ISSUE TITLE
Paperdoll Robe Layers?

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#1411]
I am not sure if I am seeing an issue, but for some reason my eye has been catching more issues of shirts (for example) being seen outside of the Robe graphic when a robe is placed on. Some of the items vanish when a robe is put on and I though shirts were one of them. When I look through the code, I see many places where clothing behavior is called out by a particular ItemID value...but adding custom clothing is problematic when the ID is hard coded. Does ClassicUO read the TileData flags for clothing? There is also a stitchen.def file but I don't know how old that was in the client files. Years ago? Maybe not even being used anymore? I just notice that this file has clothing listed and what it is supposed to hide when worn like Lord British costume or the death shroud.

**Comment by Arthrutus** [comment]
Stitchin.def was made for the old third dawn 3d client. It is not used for the 2d client. 

To clarify the issue with items "disappearing" under robes, this is because the client has hard-coded lines that declare other layers as being "used," forcing items in that spot to disappear. You can see this with the hooded shroud (Layers.Helm, tunic, arms, etc are all made invisible) as well. This is to prevent the items from displaying residual graphics from underneath the robe. 

You can hack the client and figure out which hex values adjust which layers, etc. ClassicUO won't be much help here if the client has it all hardcoded.

**Comment by Djeryv** [comment]
I actually solved this at the server level, and since nobody else has been speaking up about this...I will sum it up to the client actually doing what it is supposed to be doing.
