### ISSUE TITLE
Paperdoll Issues

### ISSUE THREAD

**Issue by aclark13** [ClassicUO/ClassicUO#203]
-No "Character Profile" Scroll on Paperdoll
-Dragging Items from your paperdoll to you pack/bag/ground causes the item to disappear from both, but upon login its still equipped

**Comment by andreakarasho** [comment]
1) ok
2) i cannot replicate it, on my pc seems ok. I'll investigate

**Comment by aclark13** [comment]
[ClassicUO.zip](https://github.com/andreakarasho/ClassicUO/files/2743221/ClassicUO.zip)
Video attached showing the disappearing clothes... #2

**Comment by jkachhad** [comment]
Started working on the profile gump. Ran into an issue where the original clients have elements that adjust their Y positions due to another expanding control (TextBox). Second issue is that our multi line text box is unable to display line breaks '\r' and '\n'.

Branch: https://github.com/jkachhad/ClassicUO/tree/profile-gump

7.0.20.0 vs ClassicUO
![image](https://user-images.githubusercontent.com/1934897/50942274-e55a3b80-143c-11e9-8b69-4445b9cc5263.png)

**Comment by andreakarasho** [comment]
This fix should resolve the item disappearing https://github.com/andreakarasho/ClassicUO/commit/75d3aa4708bcdc5740fa39b9927b078735533ff8

**Comment by SaschaKP** [comment]
this commit should have already solved the multiline problem, now every gump with multilines must use the adopted multiline boxes & entries @jkachhad 85ec02bb498f42b325ef6296231b77b0ade4d3b6

**Comment by SaschaKP** [comment]
I think this can be closed, but I will wait for the confirmation from the counterparts 💃

**Comment by andreakarasho** [comment]
the 2nd persists......

**Comment by andreakarasho** [comment]
2: was a razor problem + a wrong way to dispose ItemGump
