### ISSUE TITLE
new character creation: displays britania and not custom shard map

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#378]
When creating a new character on UO outlands , I am  unable to do so since britania trammel appears on the last screen and not the uo outlands map for selected for a city. 

alpha 5

**Comment by floyd501** [comment]
There were issues implementing this previously due to how the Outlands server sends city info (see: #237).  Not sure if that was addressed or is still in the works on the server side.  That said, even though the Britannia map shows, character creation should still work all the way through, at least on the latest release.  I believe there were some updates to character creation between Alpha 5 and now, so if it wasn't working before, check again with Alpha 8.

**Comment by SaschaKP** [comment]
should be ok, please check and eventually report
