### ISSUE TITLE
new status bar (slim)

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#540]
suggested by @Wuffa#5722 
![image](https://user-images.githubusercontent.com/26830362/59984338-9836e400-95ee-11e9-983a-cd640c8802a2.png)

this looks great, if we could also have an option to include:
a. potion cooldown timer
b. food timer

alternatively a "snap grid" build your own status bar =)

**Comment by oroechimaru** [comment]
not sure if community desires this

**Comment by SaschaKP** [comment]
this seems to be too much shard/server specific

**Comment by SaschaKP** [comment]
maybe, adding the ability to customize it, could bring the possibility, for every single person to make it as they want, but I can't tell anything else beside that

**Comment by roxya** [comment]
Would people be satisfied with a separate InfoBar gump (does not replace status bar), which is customisable with text variables (similar to how razor/steam titlebars work)?
![image](https://user-images.githubusercontent.com/7057924/60139150-bba38f80-97a4-11e9-9724-5c90ba6eb537.png)

If only because text customisation is a lot easier without limiting the user too much (e.g. you can pick two variables only, because that's the gump we designed!), and makes it totally shard independent.

(this is not an offer to make it haha, just contributing because of the discord discussion)

**Comment by andreakarasho** [comment]
@roxya is developing it out if i understood well, but it's totally different from the 3d started so.. closed. :D
