### ISSUE TITLE
Projectiles move too slow

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#594]
Not sure if bug or feature request.

Projectiles (arrows, and such) move too slowly. Probably due to the higher FPS. However, it does not look very good. Example in the video below, to the left is regular UO, to the right is CUO. In CUO the projectile seems to slowly make its way across and damage is dealt before it hits the target. The desired effect would be that the projectile never takes reaches the target after the damage is dealt.

https://imgur.com/pVuH0YQ

**Comment by andreakarasho** [comment]
fixed

**Comment by BlackTeaOutlands** [comment]
Hey! Now projectiles move too fast - you can't see them at all :)

Do they fade in? Might be that otherwise.

https://imgur.com/qALuwuc

**Comment by andreakarasho** [comment]
i made a fix yesterday

**Comment by wuffa** [comment]
Projectiles are moving way too fast now, you can hardly see some of them. They also seem to have a very long fade-in effect, only reaching a high level of opacity right at the end of the animation.

Here's how it looks in the standard client:
![steamprojectiles](https://user-images.githubusercontent.com/53117594/61718259-e90f3900-ad62-11e9-9b08-7fc6c7ae0256.gif)

And in CUO:
![cuoprojectiles](https://user-images.githubusercontent.com/53117594/61718268-ef051a00-ad62-11e9-9e6e-71941d617a7c.gif)

And this is how they were in some previous version from about 6-7 weeks ago, looking much better, but indeed a little bit slower. I timed ebolts at about this distance using my gif software and std client came to 780ms of ebolt being up and 890ms was for the old cuo version.
![cuoprojectiles1](https://user-images.githubusercontent.com/53117594/61724300-fb42a480-ad6d-11e9-9b46-cc458e0be322.gif)

So we need it more like this but a tiny bit faster. We just need to match the speed of the standard client, doesn't matter if it's sync'd with dmg or before or after, because that depends on your distance to the target.

**Comment by oroechimaru** [comment]
if u turn your fps to 15 do they slow down?

**Comment by wuffa** [comment]
Could we have the change reverted in the mean time?

I believe it was this commit: https://github.com/andreakarasho/ClassicUO/commit/36f2438e30e8112138eac29c73bb44b14766a629

Projectiles were only very slightly slower originally, they are now like 1000% too fast.

I think the original complaint of the damage hitting before the projectile does is NOT an issue, as this can happen on standard client as it depends on damage delay, distance and movement (you can see that in my first gif in my previous comment).

This is quite an issue for group pvp at the moment as ebolts are almost not visible.

**Comment by andreakarasho** [comment]
should be fixed with latest commits
