### ISSUE TITLE
Vendor Sell Text Wrapping

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#688]
Using the beta version, I notice that if the item names are long they are being wrapped down to the next line instead of making the vendor entry taller to compensate.

![image](https://user-images.githubusercontent.com/49735284/64622350-d43b4300-d3ac-11e9-9683-db107c977745.png)

**Comment by oroechimaru** [comment]
Please test dev. its good to test dev to not report bugs that are fixed. Thanks! If you are on uoo, read the pinned guides from ace. otherwise join the developer discord and use the powershell links in the downloads section on a copy of your cuo folder to a new location (updating settings.json to reflect the new folder paths).

Thanks!

**Comment by Djeryv** [comment]
Where in the changelog did it say this issue was fixed since beta was released?

**Comment by Djeryv** [comment]
Although good advice, and it did turn out to be true, I did not see in the changelog where this was fixed. So in my screenshot you can compare the fonts in the sell window to the thicker orange font in the one I compiled today. When I download a new version, I watch for bugs/fixes after that moment and if I do not see a fix for a particular issue, I assume it hasn't been discovered yet. If I were to do it any other way, I would be compiling multiple times a day just to say I am "on the most current version".

Any...close this one.

**Comment by oroechimaru** [comment]
which server do you play on? if Outlands maybe one of us could help check it out in dev. if so what location can we go to?
