### ISSUE TITLE
Opening backpack resets "counters"

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#702]
Opening your backpack will reset counters if the item is not in the standard backpack.
For example if you have bandages in a sub-backpack; every time you open your inventory the counter will reset to 0.

(I think "hotbar" would be a better name instead of "counter")

Bandage counter being reset when opening backpack due to them being in a sub-container:
![2019-09-15_21-39-39](https://user-images.githubusercontent.com/1727541/64926747-78841600-d801-11e9-835d-4e38ddb68975.gif)

Playing on UO Outlands.
Windows 10, ClassicUO Beta - 0.1.2.0

**Comment by andreakarasho** [comment]
This issue is due to what server sends.
After login, until you don't open these containers/bags server will not send to you contents.

**Comment by Hezkore** [comment]
This isn't just at start though.
If you keep items in a sub-container the counter will miss those items every time you open your backpack.
Razor doesn't seem to have this issue.

**Comment by dissident76** [comment]
I was working on the issue but RL got really busy. It is possible, just like Razor does, to keep a constantly updated cache. I will finish it when I have time -it was 90% functional when I had to stop

**Comment by LeopoldUOR** [comment]
I think Razor does this by auto-searching containers (and any sub-containers).  It gives the option to ignore pouches, so that people can still use explosion pouches for paralyze.  So when you first log in, Razor will open your main pack which causes it to search all sub-containers.  Anytime you re-open your main pack it should search all sub-containers.  Any time you add a new container to your main pack, it should search that container, and all sub-containers.  I think this would make it so the CUO counters will work just like the Razor counters.
