### ISSUE TITLE
[Request] Invert shift + drag stack

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#706]
Atm. shift + drag moves an entire stack.
I would like an option to invert that behaviour; so that dragging always moves the entire stack, and shift + drag asks for quantity.

**Comment by Alias-Alan** [comment]
I believe this is intentional, on old client shift drag was the complete stack. Dragging normally always gave you to quantity gump.

**Comment by Hezkore** [comment]
Yes that is most likely the case.
But this is a request for an option to invert it.
I hardly ever input quantity, so the default option (at least to me)

**Comment by Hezkore** [comment]
Yes that is most likely the case.
But this is a request for an option to invert it.
I hardly ever input quantity, so I'd like that as shift + drag instead.
That would also put it in line with other more modern games.

(Closed issue by mistake because phones are annoying)

**Comment by Hezkore** [comment]
It's not even that hard to add.
I made this on my lunch break today:
![2019-09-23_17-58-56](https://user-images.githubusercontent.com/1727541/65442078-d7621480-de2b-11e9-8099-8320d27c77a3.gif)

**Comment by binff04** [comment]
In modern games, like WoW, for example, you always drag the entire stack and to split it you have to hold shift + click the stack.

I also find this behavior more useful because most of the time you drag piles of gold, stacks of potions entirely and only occasionally you need to split them up.

Anyway, it's a neat option to have in the modern client.

**Comment by binff04** [comment]
This issue can be closed now -- the feature is already merged into the dev branch.
