### ISSUE TITLE
Target Cursor Wants to Grab Objects Instead

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#732]
I compiled the dev yesterday and this issue has been going on for awhile. If I were to target an object (like double click scissors) and then target an object to cut...it mostly picks up the object instead of cutting it. It appears if I quickly tap my mouse button, it will do the target function but a normal button press picks it up.

**Comment by LeopoldUOR** [comment]
I've noticed this type of behavior as well.  I figured it was just my muscle memory that needs to adjust to CUO rather than the old client.  Here is when I notice it:  My hotkey for loot restock agent is CTRL+F.  When loot bags inside a container (e.g. NPC camp chest) very quickly, the cursor will pick up the bag rather than restock from it.  This doesn't happen for me on OSI client, but happens very frequently on CUO.  I'll go do some NPC camps today and report back with more details if I can figure out if there is some way to make it happen every time.

**Comment by andreakarasho** [comment]
I tried, but honestly i didn't see the issue.
You have 2 way to pickup items:
- stay with L click pressed over the item for ~1s
- move mouse over the item for 5px

**Comment by Djeryv** [comment]
Like Issue #739 ...if I don't use RAZOR with CUO I don't have an issue either. You are starting to convince me to dump razor...which I can because I only used the middle mouse button feature.

**Comment by Djeryv** [comment]
Wait, now that I played some more today I am still having the issue...but it coincides with the hover over box for AOS shards. A T2A style shard does not have this hover box when you put a cursor over the item so others may have not noticed the issue. I think you would need to offset the hover window like the original client does...so the hover text window is not over the item.

**Comment by andreakarasho** [comment]
Do you mean the Tooltip?
If yes:
- tooltip is enabled by server or by client version
- tooltip doesn't have collision. It is displayed and stop

What CUO version are you running?

**Comment by Djeryv** [comment]
You and I were chatting on Sunday...where I kept compiling your latest devs. But I think that is all moot because I am thinking it is some type of mouse-click delay issue that doesn't exist in the original client. This means, I have to be very deliberate on how fast I click that mouse button to select a target. Holding the button too long/quick changes the behavior from selecting to grabbing.

**Comment by LeopoldUOR** [comment]
I've played around with this quite a bit, and I think that at least what I was experiencing is that CUO is much more sensitive to mouse movements than the old client.  I noticed that it matters which surface I use my mouse on. Sometimes when I try to target a rune after casting recall it picks the rune up.  Other times when I am restocking from a bag inside my bank box or a container it picks the bag up.  If I am very careful to not move the mouse at all while clicking it doesn't happen.

**Comment by andreakarasho** [comment]
News?

**Comment by LeopoldUOR** [comment]
This does not appear to be a problem anymore, at least for me.  Either you made some change which fixed it, or my muscle memory adjusted to the CUO client.  But I suspect it is something you adjusted, because it feels a lot less "sticky" than it did before, even if I am intentionally moving the mouse slightly while trying to target an item in my pack.
