### ISSUE TITLE
AttackSelectedTarget & UseSelectedTarget

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#766]
Now that Select Next/Prev and Nearest is implemented; it would be super nice if AttackSelectedTarget and UseSelectedTarget were implemented.

I guess AttackSelectedTarget would use `GameActions.Attack()` and UseSelectedTarget would use `GameActions.DoubleClick()`.

I'd implement this myself, but I'm not exactly sure the difference between "Targeted" and "Selected".
And I don't want to spend time on a pull request that might be incorrect or ignored.

**Comment by Stallind** [comment]
What's your discord name?

**Comment by Hezkore** [comment]
Always Hezkore, everywhere.
Hezkore#3356

**Comment by binff04** [comment]
What about some clarification here about what is "selected" target and what is "last target"?

From my understanding, in terms of iterating through the list of mobiles available in the update area, "selected" may be the same as "last target"... Otherwise, "last target" may be related to only the target that was pointed by targeting cursor and not selected by iterating through next/previous/nearest.

Any thoughts?

**Comment by roxya** [comment]
I think it's appropriate to have LastTarget and SelectedTarget as distinct entities, so that clicking something else doesn't change your SelectedTarget.

If it works like that, it will help a lot to have a dedicated indicator for SelectedTarget. Standard client has the "new target system" graphic but I suppose it isn't in every client version's art files, so building one in CUO may be the way to go.

**Comment by roxya** [comment]
I think it works like this in standard:

Select Target (e.g. Select Nearest) sets both SelectedTarget and LastTarget

LastTarget and CurrentTarget now refer to the "selected" target.

Targeting something else (with click) will change LastTarget but not SelectedTarget

Now LastTarget will target the last targeted, SelectedTarget will still target the one we found with Select, without resetting LastTarget.

Then you have AttackLast (last target) and AttackSelectedTarget.

**Comment by Hezkore** [comment]
Yeah... this feels like something I don't want to fiddle with hehe.
I did find that the "AttackLast" macro does attack my target/selected mobile/whatever, so I'm happy.

**Comment by binff04** [comment]
@roxya Okay, I get it, this is how I also thought it should be implemented, but this is as confusing as it is flexible.

What if we will just simplify some things here a bit? What if `LastTarget` will always be something (mobile or object) that we targeted with target cursor or selected via `Select{Next|Previous|Nearest}` macros?

**Comment by binff04** [comment]
Otherwise, for full flexibility we need: last combatant (last mobile or object character attacked), last target (last mobile or object we pointed using "target" cursor), last selected mobile/object (last mobile or object selected via `Select{Next|Previous|Nearest}` macro action).

**Comment by andreakarasho** [comment]
added
