### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by rdegelo** [ClassicUO/ClassicUO#77]
Hey... I see that you are actively working on this project and I wonder if I can contribute? I played Ultima Online for more than 10 years, I don't play anymore but would be nice to work in such a project.

Let me know, thanks!

**Comment by 3HMonkey** [comment]
Hello Sir,
yeah pretty true this is in active development status. Thank you for your interest. How would you describe your c# skills especially .Net core and/or fna/xna/monogame skills? Btw since we are a really active team who develop a mature project, we are always looking to expand the main core team. 

Greetings 3HMonkey

**Comment by rdegelo** [comment]
I am a software developer engineer and I have 9 years of professional experience with c#, very basic experience with XNA/Monogame to be honest.
It would be good to work with such an exciting project. 

Thanks!

**Comment by 3HMonkey** [comment]
We are using discord internally. Can you send me your name/id?

**Comment by rdegelo** [comment]
Degelo#6800
